### PR TITLE
xmlcheatsheet.md

### PR DESCRIPTION
**Pull request by nihal-soni**
Added Xml Cheatsheet

### CODE REVIEW

**Review by onecompiler-ops — CHANGES_REQUESTED** [review]
CheatSheet metadata is missing/invalid format, please refer to other cheat sheets to see how to add that. Also please use all lowercase letters for file name

**Comment by nihal-soni** [comment]
Ok 
Can I create again.

**Comment by onecompiler-ops** [comment]
Fix in this PR itself

**Comment by nihal-soni** [comment]
ok

**Comment by nihal-soni** [comment]
CheatSheet metadata is missing/invalid format, where  
where

**Comment by onecompiler-ops** [comment]
lifted from here https://cheatography.com/nqramjets/cheat-sheets/xml-1-0/

**Pull request closed without merging**
