### PR TITLE
UBUNTU-22.04 Cheat Sheet added

### PR DESCRIPTION
**Pull request by Suryansh1720001**

### CODE REVIEW

**Comment by Suryansh1720001** [comment]
I have added the cheat-sheet @onecompiler . Now, you can verify and merge this. 
And Please also add hacktoberfest-accepted label in this.

**Review by onecompiler-ops — CHANGES_REQUESTED** [review]
CheatSheet metadata is missing/invalid format, please refer to other cheat sheets to see how to add that. Also please use all lowercase letters for file name

**Comment by Suryansh1720001** [comment]
Hello @onecompiler-ops 
The changes are done. Now you can verify the file and merge it accordingly.
Thank you

**Comment by onecompiler-ops** [comment]
Plagiarized content detected. You have been blocked from this community.

**Pull request closed without merging**
