### PR TITLE
Create cpp_cheatSheet.md

### PR DESCRIPTION
**Pull request by Anubhav-Ghosh1**
I have compted and issue assigned to me for adding file for cpp cheatsheet

### CODE REVIEW

**Comment by onecompiler-ops** [comment]
duplicate

**Comment by Anubhav-Ghosh1** [comment]
Hey go and see I have asked to add cpp cheatsheet first someone else also mad eit after it was assigned to me

**Comment by Anubhav-Ghosh1** [comment]
I was the first to ask and to get assigned that task

**Comment by onecompiler-ops** [comment]
cpp cheat sheet exists from more than 2 years

**Pull request closed without merging**
