### PR TITLE
Added the Rust cheatsheet as part of Hacktoberfest - Issue #95

### PR DESCRIPTION
**Pull request by Prahmodh-R**
This is my PR to issue https://github.com/onecompiler/cheatsheets/issues/94 as part of Hacktoberfest 2022. I've added a cheatsheet for Rust covering all the major functionalities and syntax. Could you please review my PR and merge it @onecompiler-ops

### CODE REVIEW

**Review by onecompiler-ops — CHANGES_REQUESTED** [review]
file name has space
metadata keys are in the wrong format

**Comment by Prahmodh-R** [comment]
@onecompiler-ops Could you please explain about the metadata keys part, I didn't get you properly

**Comment by Prahmodh-R** [comment]
@onecompiler-ops Could you please explain about the metadata keys part, I didn't get you properly

**Comment by Prahmodh-R** [comment]
@onecompiler-ops I've updated the file and made the necessary changes, please review and merge it as part of Hacktoberfest

**Review by onecompiler-ops — APPROVED** [review]

**Pull request merged**
