### PR TITLE
Created CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by trishitchar**

### CODE REVIEW

**Comment by onecompiler-ops** [comment]
This needs some code changes from one compiler to support, we will review and merge later

**Comment by trishitchar** [comment]
@onecompiler-ops
Your project don't have any contributing guideline. It's better to add a contribution process I think so.
Thank you.

**Comment by onecompiler-ops** [comment]
We will have a look at it, and merge today

**Comment by trishitchar** [comment]
@onecompiler-ops 
Can you process it further, please?

**Pull request closed without merging**
