### PR TITLE
Added Figma.md

### PR DESCRIPTION
**Pull request by Spandita-dwivedi**
Added Figma.md Cheat sheet , Very useful for Designers.

### CODE REVIEW

**Review by onecompiler-ops — CHANGES_REQUESTED** [review]
CheatSheet metadata is missing/invalid format, please refer to other cheat sheets to see how to add that. Also please use all lowercase letters for file name

**Comment by Spandita-dwivedi** [comment]
Sure sir !

**Comment by Spandita-dwivedi** [comment]
Updated The format.

**Review by onecompiler-ops — CHANGES_REQUESTED** [review]
rename the file to `figma.md`

**Comment by Spandita-dwivedi** [comment]
Screenshot (1)


Renamed the file to figma.md

**Comment by Spandita-dwivedi** [comment]
Added Tables and made the format more clear

**Review by onecompiler-ops — APPROVED** [review]

**Pull request merged**
