### PR TITLE
Updated triggers in mysql.md

### PR DESCRIPTION
**Pull request by arshanand1**
Added trigger functions in mysql.md

### CODE REVIEW

**Comment by onecompiler-ops** [comment]
file name got changed to `mysql.md` can you rebase

**Comment by arshanand1** [comment]
Can you please elaborate a bit? I did not get the issue

**Comment by onecompiler-ops** [comment]
there is no `my-sql.md` file now, it got changed to `mysql.md`

**Comment by arshanand1** [comment]
my forked repository still shows my-sql.md can you tell me how i can update it?

**Pull request closed without merging**
