### PR TITLE
Added Django Cheat Sheets

### PR DESCRIPTION
**Pull request by Rituraj-13**
Django Cheat Sheet contains the important commands along with their descriptions.

### CODE REVIEW

**Comment by Rituraj-13** [comment]
**Link of the issue :-** [Click here](https://github.com/onecompiler/cheatsheets/issues/105)

**Review by onecompiler-ops — CHANGES_REQUESTED** [review]
please use the filename as django.md

**Comment by Rituraj-13** [comment]
Hey @onecompiler-ops, changed the file name, kindly have a look.

**Comment by onecompiler-ops** [comment]
We can see, this is copy pasted from here https://github.com/lucrae/django-cheat-sheet/blob/master/README.md
Sorry, we can't accept copy-written content/ lifted content from different websites/ other users' GitHub content. 
Please produce original content

**Comment by Rituraj-13** [comment]
> We can see, this is copy pasted from here https://github.com/lucrae/django-cheat-sheet/blob/master/README.md
> Sorry, we can't accept copy-written content/ lifted content from different websites/ other users' GitHub content. 
> Please produce original content 

Sorry, I apologise for the inconvenience.

**Pull request closed without merging**
