### PR TITLE
Add predefined function of c and java string

### PR DESCRIPTION
**Pull request by MananSharma2710**
Make changes in c.md by adding a predefined function section(Sublist and listcat).
Add predefined java string function in java-strings.md.

### CODE REVIEW

**Comment by onecompiler-ops** [comment]
Closing this PR as this does not meet the quality guidelines.

**Comment by MananSharma2710** [comment]
Hi

Please let me know the quality guidelines so that I can work accordingly to
contribute to your work.

**Comment by onecompiler-ops** [comment]
We will add details on that. Few key points 
1. Do not use your name on exmaples
2. Use good formatting, follow Markdown where ever possible 
3. Use Tutorials repo for detailed information

**Comment by MananSharma2710** [comment]
Sure, will do that.

**Pull request closed without merging**
