### PR TITLE
Update html.md

### PR DESCRIPTION
**Pull request by anant2003**

### CODE REVIEW

**Comment by onecompiler-ops** [comment]
Fix merge conflicts

**Comment by anant2003** [comment]
Now I have fixed merge conflicts.

**Comment by anant2003** [comment]
Please accept my PR as I have fixed merge conflict.

**Review by kshitijmishra27 — APPROVED** [review]
good work

**Comment by anant2003** [comment]
My PR not closed yet and in hactoberfest profile also Not accepted is showing.

**Comment by kshitijmishra27** [comment]
> My PR not closed yet and in hactoberfest profile also Not accepted is showing.

because its not merged till yet

**Comment by anant2003** [comment]
So merge it . Or I have to some changes in it it's closed now ?

**Comment by onecompiler-ops** [comment]
It's closed

**Pull request closed without merging**
