### PR TITLE
Added new java versions

### LINKED ISSUE #34: Add new java versions
Add the new java versions to https://github.com/onecompiler/cheatsheets/blob/master/java-versions.md

### PR DESCRIPTION
**Pull request by harikesh409**
Closes #34

### CODE REVIEW

**Comment by onecompiler-ops** [comment]
@harikesh409  thanks for the contributions

**Comment by harikesh409** [comment]
@onecompiler-ops 
Can you please add the required hactoberfest labels also to it.

**Comment by onecompiler-ops** [comment]
@harikesh409 please mention the labels in the comment, we will add them

**Comment by harikesh409** [comment]
@onecompiler-ops 
Please add `hacktoberfest-accepted` to the PR and `hacktoberfest` label to the issue and repo.

**Comment by onecompiler-ops** [comment]
done!

**Pull request merged**
